# camera
THRESHOLD_MULTIPLIER: int = 3
EASING_MULTIPLIER: int = 2

# world
SCORE_OFFSET: int = -(THRESHOLD_MULTIPLIER - 1)

# environment
GROUND_HEIGHT_MULTIPLIER: int = THRESHOLD_MULTIPLIER * 2
GROUND_START_MULTIPLIER: int = THRESHOLD_MULTIPLIER
WATER_GRID_SPACING_MULTIPLIER: int = 2
WATER_STARTING_ROW_ID: int = THRESHOLD_MULTIPLIER - 1

# log
MAX_SPEED_MULTIPLIER: int = 5
LOG_STARTING_ROW_ID: int = THRESHOLD_MULTIPLIER + 1

# player
SIZE_DECREASE_CONSTANT: int = 5
RECT_SIZE_DECREASE: float = 1 / SIZE_DECREASE_CONSTANT
MARGIN_DECREASE: float = (SIZE_DECREASE_CONSTANT * 2 - 1) / (SIZE_DECREASE_CONSTANT * 2)
